---
- hosts: ios
  name: Configure interfaces and test connection
  gather_facts: false
  vars:
    probes_sent: 1
  tasks:

    - name: Generate Interface configuration
      template:
        src: "interface_config.j2"
        dest: "intf_configs/{{ inventory_hostname }}.cfg"

    - name: Configurable interfaces IP address
      ansible.netcommon.cli_config:
        config: "{{ lookup('template', 'interface_config.j2') }}"

    - name: Ping checks
      napalm.napalm.napalm_ping:
        hostname: "{{ inventory_hostname }}"
        destination: "{{ item }}"
        count: "{{ probes_sent }}"
      loop: "{{ neighbors }}"
      register: output

    - name: Register results per ping
      ansible.builtin.set_fact:
        host_results: "{{ host_results|default([]) + [ {
            'dest': item.item,
            'packet_loss': item.ping_results.success.packet_loss,
            'percentage': item.ping_results.success.packet_loss % probes_sent
             } ] }}"
      loop: "{{ output['results'] }}"
      ignore_errors: true

    - name: Register necessary variables
      ansible.builtin.set_fact:
        date: "{{ lookup('pipe', 'date +%Y%m%d%H%M') }}"

    - name: Generate csv report
      ansible.builtin.template:
        src: "ping_report.j2"
        dest: "reports/report_{{ date }}.csv"
      delegate_to: localhost
      run_once: true

    - name: Verify Interfaces' IP address
      ansible.builtin.assert:
        that: item['value']['ipaddr'] | ipv4
      loop: "{{ interfaces | dict2items }}"

    - name: Verify neighbor's IP address
      ansible.builtin.assert:
        that: item | ipv4
      loop: "{{ neighbors }}"
