---
- hosts: ios, eos
  name: Ping checks for reachability
  gather_facts: false
  vars:
    probes_sent: 1
  tasks:

    - name: Ping checks
      napalm.napalm.napalm_ping:
        hostname: "{{ inventory_hostname }}"
        destination: "{{ item }}"
        count: "{{ probes_sent }}"
      loop: "{{ ping_destinations }}"
      register: output

    - name: Register results per ping
      ansible.builtin.set_fact:
        host_results: "{{ host_results|default([]) + [ {
            'dest': item.item,
            'packet_loss': item.ping_results.success.packet_loss,
            'percentage': item.ping_results.success.packet_loss % probes_sent
             } ] }}"
      loop: "{{ output['results'] }}"
      ignore_errors: true

    - name: Print
      ansible.builtin.debug:
        var: host_results

    - name: Register necessary variables
      ansible.builtin.set_fact:
        date: "{{ lookup('pipe', 'date +%Y%m%d%H%M') }}"

    - name: Create csv file and add header
      ansible.builtin.lineinfile:
        dest: "reports/report_{{ date }}.csv"
        line:
          Device,Destination,Success Rate,Status
        create: true
        state: present

    - name: Write report into .csv file
      ansible.builtin.lineinfile:
        insertafter: EOF
        dest: "reports/report_{{ date }}.csv"
        line: "{{ inventory_hostname }},{{ item['dest'] }},{{ item['packet_loss'] }},{{
          item['percentage'] }}%,{% if item['percentage']>=80 %}Success{% else %}Failure{% endif %}"
      loop: "{{ host_results }}"
